### PR TITLE
removed rules that block (custom) js and css

### PR DESCRIPTION
**Pull request by dataneger**
Google has new ranking factors
- site speed
- mobile friendly

These ranking factors require google to render and parse the CSS and JS files.
Default robots.txt blocks these files from being indexed and therefor you get a low score on these ranking factors. I removed the lines that where blocking.

### CODE REVIEW

**Comment by Remo** [comment]
@dataneger any chance you can update your pull request to take care of the robots.txt during the upgrade process too?

**Comment by dataneger** [comment]
I will but end of the week when i have some time to make a good solution.

**Comment by hissy** [comment]
Let's add trailing slash to each rule. See an another discussion #1880

**Comment by Remo** [comment]
I agree, trailing slashes are important and removing the entries mentioned above is too. It's definitely something I'd merge, I'd just like to have an upgrade procedure that tries to clean up robots.txt as far as possible.

**Comment by hissy** [comment]
I think some users updated their robots.txt manually.

**Comment by Remo** [comment]
Definitely, but searching for a certain line and removing or changing it is fairly simple.

**Comment by Remo** [comment]
@dataneger any chance you can finish this PR?

**Comment by hissy** [comment]
I tried to make upgrade script, and I used file type syntax in additional rules. I think we have to allow Googlebot to access to block assets, package assets, and core assets in updates/ directory. Of course, this pull request is still draft, so I'd like to other's opinion...

**Pull request closed without merging**
