### PR TITLE
Enhancement importing page structure

### PR DESCRIPTION
**Pull request by hissy**
Add ability to import user and public date same as 5.7 ContentImporter

### CODE REVIEW

**Comment by Remo** [comment]
can you please link the PR for the 5.7 repo?

**Comment by hissy** [comment]
There's no PR. ContentImporter class is updated by core team.

https://github.com/concrete5/concrete5-5.7.0/blob/develop/web/concrete/src/Backup/ContentImporter.php

**Comment by Remo** [comment]
I see, thanks!

**Comment by hissy** [comment]
thanks!

**Pull request merged**
