### PR TITLE
Static Block Template Issue

### PR DESCRIPTION
**Pull request by JeRoNZ**
This is perhaps a slightly esoteric one, I have a block template which is in packages/my_package/blocks/block_type/templates/my_template/view.php. Attempting to use the block in a page template statically, e.g.

```php
$search = BlockType::getByHandle('search');
$search->controller->title = 'search';
...
$search->render('templates/my_template');
```

Doesn't work because the $bFilename is being tested to see if it's a directory - which it isn't. Fix is to test $bFilenameWithoutDotPhp rather than $bFilename

See https://www.concrete5.org/developers/bugs/5-6-3-1/pacakge-block-template-not-found-when-block-rendered-statically-/

### CODE REVIEW

**Comment by Remo** [comment]
doesn't affect that the core functionality when you select a custom block template?

**Comment by JeRoNZ** [comment]
No. It just fixes the one case where static block usage fails to find the template, if that template is in packages/handle//blocks/handle/templates/template_name/view.php

For example, in my /blocks folder I have search/templates/template_one.php and search/templates/template_two/view.php.

In package/handle/blocks I have search/templates/template_three.php and search/templates/template_four/view.php.

Adding a search block to the page and setting a custom template shows four templates available and all are functional when selected.

By contrast, four blocks added to the theme using the four templates like this:
```php
...
$search->render('templates/template_one');
...
$search->render('templates/template_two');
...
$search->render('templates/template_three');
...
$search->render('templates/template_four');
```php

template four is not found and the view reverts to the default with the current 5.6.3.2 code base. If I switch to my patched code, it is found and renders as I intended. The four templates continue to show up when adding a block to an area when using the patched code.

Just for completeness, i tried overriding templates three and four by dropping them into the /blocks hierarchy and they do indeed override the package versions.

**Comment by Remo** [comment]
I understand what it fixes, I just want to be sure it doesn't break anything which is working right now..                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   From: JeRoNZSent: Saturday, January 10, 2015 21:07To: concrete5/concrete5Reply To: concrete5/concrete5Cc: Remo LaubacherSubject: Re: [concrete5] Static Block Template Issue (#1871)No. It just fixes the one case where static block usage fails to find the template, if that template is in packages/handle//blocks/handle/templates/template_name/view.php

For example, in my /blocks folder I have search/templates/template_one.php and search/templates/template_two/view.php.

In package/handle/blocks I have search/templates/template_three.php and search/templates/template_four/view.php.

Adding a search block to the page and setting a custom template shows four templates available and all are functional when selected.

By contrast, four blocks added to the theme using the four templates like this:

...
$search->render('templates/template_one');
...
$search->render('templates/template_two');
...
$search->render('templates/template_three');
...
$search->render('templates/template_four');
```php

template four is not found and the view reverts to the default with the current 5.6.3.2 code base. If I switch to my patched code, it is found and renders as I intended. The four templates continue to show up when adding a block to an area when using the patched code.

Just for completeness, i tried overriding templates three and four by dropping them into the /blocks hierarchy and they do indeed override the package versions.

—Reply to this email directly or view it on GitHub.

**Comment by JeRoNZ** [comment]
Sure - hopefully the test cases above show that it doesn't break anything.

**Comment by Remo** [comment]
Okay your chance makes sense to me, but
1. Why didn't you change `$this->baseURL`?
2. Do you know why `$this->basePath` isn't set in that condition? Not a change you've made, but I'd like to understand what the whole things does.

I know I'm a bit annoying, but I want to be sure about changes like this..

**Comment by JeRoNZ** [comment]
1) Because the issue was that a filename was being tested to see if it was a directory - which would always fail. When a block is used statically, computeView() receives a BlockView object, not a Block object. There's a comment in ComputeView()  that says:
```php
// The filename might be a directory name with .php-appended (BlockView does that), strip it.
$bFilenameWithoutDotPhp = $bFilename;
```
So since $bFilenameWithoutDotPhp is the directory we likely want testing this is much better.

computeView() seems to get called more than once per block, and I can see that static blocks appear use the setBlockCustomRender() method (called from core/libraries/block_view.php), but page blocks don't. Thus the routes into computeVIew() are different and potentially have different data to work with.

**Comment by Remo** [comment]
@JeRoNZ I created a new PR as you've commited more changes into this branch. If those changes are required, create a new PR please. Tracking changing is much easier if the pull request matches the actual changes, thanks!

**Pull request closed without merging**
