### PR TITLE
Make news flow work again

### PR DESCRIPTION
**Pull request by hissy**
We can not read Newsflow now. Let's make it works again.

### CODE REVIEW

**Comment by JohntheFish** [comment]
My main issue with newsflow is how often it simply hangs while waiting for c5.org. Possibly going off topic for this pull, but can anything be done to cancel the overlay if c5.org does not respond within a reasonably short timeout? Or just have a cancel X in the top right ot the newsflow while it is 'waiting' so users who get fed up can cancel it without having to refresh the whole page?

**Comment by Remo** [comment]
@JohntheFish I completely agree, often found it super annoying. Not sure how it works in 5.7, but shouldn't we focus the effort on the new version? People like us are able to come up with a custom configuration where the newsflow is disabled pretty easily..

**Comment by hissy** [comment]
I agree too, but that is an another discussion. I think this is just a bug.

**Comment by Remo** [comment]
I agree

**Pull request merged**
