### PR TITLE
Update tinyMCE to 3.5.11.

### PR DESCRIPTION
**Pull request by HeikkiYlipaavalniemi**

### CODE REVIEW

**Comment by Remo** [comment]
@katzueno this PR contains some files Heikki modified after some of my feedback and his tests. I'll run some more tests myself but if you find some minutes to spare, I'd appreciate some feedback. Breaking the content block would be pretty bad, but I'm eager to merge this as I believe we should have a properly working 5.6 for a while longer. (Talking about the link issue with IE11)

**Comment by katzueno** [comment]
@Remo 
I finally had time to run some tests on IE11 with IE.Modernizer VirtualBox.

- Regular concrete5 theme works
- Office Theme works

I haven't had time to check other browsers yet.

**Comment by katzueno** [comment]
Here is Things to Test.
Please, can anyone volunteer to test these?

## Browser to test

1. IE9
2. IE10
3. Safari
4. Chrome
5. Firefox
6. Opera

* I've tested with IE11. And it works very well.
* If anyone bother to test IE8, please go head.

## Checklist: What to test

- Add a image button
- Add a link button
- Add a file button
- TinyMCE buttons
    - Simple theme: all buttons
    - Advanced Theme: all buttons
    - Offie Theme: all buttons

You can change the theme by going to [Dashboard] - [Basics] - [System and Settings] - [Rich Text Editor]
Or directly go to [concrete5]/index.php/dashboard/system/basics/editor/ by admin account.

**Comment by Hypocrite** [comment]
I have tested it with Chrome and with other themes. That works fine.

I could try to find the time to Firefox also.

**Comment by HeikkiYlipaavalniemi** [comment]
Tested with Firefox 35 on OS X and everything seems to work fine. I tested with all the themes
* adding/editing links
* adding images
* adding tables
* adding links from File Manager
* adding images from File Manager

**Comment by HeikkiYlipaavalniemi** [comment]
Tested also Safari 8.0.3 quickly and didn't find any problems. Tested adding/editing links and images with different themes. Also tested adding and editing tables.

**Comment by Remo** [comment]
IE 11.0.9879.0 on Windows 10 doens't work, can't insert links. Probably because TinyMCE is sniffing the user agent string. I guess we'll soon have to merge another fix )-:

**Comment by HeikkiYlipaavalniemi** [comment]
That could be interesting if tinyMCE is not updating 3.5.x branch anymore.

But Windows 10 is still a development version. Probably they will make changes to IE also. I don't think they want to break a lot of sites in Windows 10 vs. Windows 7/8.

Also the new Spartan browser is coming in Windows 10 and that might break everything. :)

**Comment by Remo** [comment]
Spartan will have a new UA string, already breaks two sites I know use UA sniffing...

> Microsoft’s Spartan browser uses the Chrome UA string
http://www.davevoyles.com/microsofts-spartan-browser-uses-chrome-ua-string/

**Comment by HeikkiYlipaavalniemi** [comment]
That's... interesting.

**Comment by Remo** [comment]
does spellchecking work for you? There's something odd with the plugin, check this screenshot

image

**Comment by HeikkiYlipaavalniemi** [comment]
The whole spellchecking seemed to have change a lot. There were a lot of files removed compared to the old version and the new one. I didn't have time to test that yet.

**Comment by Remo** [comment]
I don't think I ever used that plugin, not sure it ever worked, but it doesn't seem to work for me now. It's also strange that a file in the spellchecker directory is called TabFocusPlugin.

**Comment by HeikkiYlipaavalniemi** [comment]
I think it might need more configuration to make it work in 3.5. It doesn't seem to work out of the box:
http://www.tinymce.com/wiki.php/Plugin3x:spellchecker

Mainly this:
3. Open up the config.php file you just unziped in the spellchecker folder.
4. Uncomment the spellchecker engine that you wish to use for example "GoogleSpell".
5. If you use the command line PSpell/ASpell class, you may need to configure the following paths "PSpellShell.aspell" and "PSpellShell.tmp".

**Comment by Remo** [comment]
I can't even get the spellchecker button to show up..

**Comment by akodde** [comment]
I think GoogleSpell needs an API-key these days. Don't people use browser add-ons today to check spelling?

**Comment by Remo** [comment]
See above, I'm stuck a step before API key related stuff.. Well, I don't need that plugin, it's just about removing a thing people might be using.

**Comment by Remo** [comment]
@HeikkiYlipaavalniemi I downloaded tinyMCE 3.5.11 and checked the file `/web/concrete/js/tiny_mce/plugins/spellchecker/editor_plugin.js`. It looks different compared to the one in your commit, can you please check that?

**Comment by Remo** [comment]
all files called `editor_plugin.js` are minimized in my downloaded ZIP?

**Comment by HeikkiYlipaavalniemi** [comment]
I downloaded the Spellchecker 2.0.61 plugin from here:
http://www.tinymce.com/download/download.php

That also comes with editor_plugin.js and editor_plugin_src.js.

Not sure which one we should use. The instructions for the Spellchecker plugin say that you should download the whole spellchecker plugin.

**Comment by HeikkiYlipaavalniemi** [comment]
Yes, the JS files are minimized in the original download but I thought it would be easier to notice differences if we use the non minimized versions. So I replaced the minimized .js files with the _src.js file. Code should be the same.

**Comment by HeikkiYlipaavalniemi** [comment]
I was able to get Spellchecker button to show up. Needed to use the js files from tinyMCE 3.5.11 download and other files from the spellchecker plugin.

**Comment by HeikkiYlipaavalniemi** [comment]
Added all the missing spellchecker files and copied the js files from tinyMCE 3.5.11. This set seems to fix the spellchecker for me at least.

**Comment by Remo** [comment]
The button shows up, but I'm not sure what should happen then. I disabled the spellchecker in chrome and put some typos in my content but nothing happens..

**Comment by HeikkiYlipaavalniemi** [comment]
Check my screenshot from above. It underlines the mistakes with red. What do you have in your config in concrete5?

**Comment by Remo** [comment]
are you sure those are from the spellchecker plugin and not from your browser?

**Comment by HeikkiYlipaavalniemi** [comment]
True. :)

**Comment by Remo** [comment]
this is what it used to do

image

**Comment by HeikkiYlipaavalniemi** [comment]
I think the spellchecker is not very needed feature. 

If we really want a spellchecker, this seems like a good option:
http://jquery-spellchecker.badsyntax.co/tinymce.html

**Comment by Remo** [comment]
Personally I completely agree, I'm just worried that we're taking something away which might be in use.. hmm

**Comment by HeikkiYlipaavalniemi** [comment]
Yeah, I can take a look if I could figure out what the problem is.

The jquery spellchecker is not really a option because we would have to configure tinyMCE completely again and change version etc.

**Comment by Remo** [comment]
not sure, maybe we can simply ask around in the forum and see what feedback we get.. Probably won't get a lot of feedback though

**Comment by HeikkiYlipaavalniemi** [comment]
What version of the spellchecker did not get that screenshot from? Reading through comments from Google, it seems that there has been problems with the Google spellchecker before and the other spellchecker options need server side support.

From the install instructions:
If you wish to use the PHP integrated PSpell you need to have PSpell/Aspell installed on the server, as well as the dictionaries you wish to use and have this compiled with PHP. Read more about this on the PHP website or use Google to learn more. Use the following script to test that PSpell is working correctly before trying the TinyMCE spellchecker, as the PSpell error messages aren't optimal.

**Comment by Remo** [comment]
I took it from a 5.6.3.2 site. Well, if it doesn't work by default I doubt that many people are using it and those who managed to configure PSpell/Aspell should be able to get it running again. Not perfect but should be okay if we keep it how it is..

**Comment by HeikkiYlipaavalniemi** [comment]
Yeah, at least all the needed files are there again. You just have to configure it.

I am kind of sceptical how many users really have enabled the spellchecker if 

A) Google service is down which is the default in the config file.
B) You need to edit files from the core folder to change from Google to PSpell.

**Comment by HeikkiYlipaavalniemi** [comment]
Seems like WordPress has been in the same boat:
http://www.brokentone.com/blog/2566/

**Comment by katzueno** [comment]
We could remove the buttons from it.

Also I suggest to remove the "Preview" TinyMCE button from "Office Theme".
It hasn't been working for a long time.

TinyMCE Preview

I think we could just remove the spellchecker and preview buttons.
I'm more than happy to send you PR after we merged the TinyMCE 3.5.11

We've checked with FF 36.0.0.1. It works fine.

**Comment by HeikkiYlipaavalniemi** [comment]
The close button in Preview is easy to fix.
For some reason the button is hidden with CSS.

**Comment by HeikkiYlipaavalniemi** [comment]
I think the close button has been hidden by default for all inline popups.

It isn't a problem for other popups such as HTML view because there is a button to save or cancel the changes. But there are no buttons in the Preview popup so there is no way to close the popup.

Easiest fix would be to add the default tinyMCE close button to all popups. Other option would be to try to add the same X icon which is in the concrete5 theme but that might require a bit more work.

**Comment by Remo** [comment]
I assume no one cares about this button as it never worked.. I also wonder if it's useful for anything - the actual preview happens in the page when you close the content block. Does anyone see a benefit of this button?

**Comment by HeikkiYlipaavalniemi** [comment]
Probably pretty useless.

I haven't just yet found where we can edit the default configutations for the different themes? We would just need to edit the toolbar and remove the Preview button.

I would probably also remove the Spellcheck button.

**Comment by Remo** [comment]
I vote for "remove the useless stuff"
> https://github.com/concrete5/concrete5/blob/master/web/concrete/core/helpers/tinymce.php

**Comment by katzueno** [comment]
Thanks. I'm totally fine with removing spellchecker and preview.

**Pull request merged**
