### PR TITLE
Fix datepicker bug in non US languages

### PR DESCRIPTION
**Pull request by hissy**
Bugtracker: http://www.concrete5.org/developers/bugs/5-6-3-2/saved-ampm-date-attributedoes-not-loaded-on-the-panel/

### CODE REVIEW

**Comment by katzueno** [comment]
Hey, can anyone review this PR to fix the date picker?

**Comment by Remo** [comment]
@katzueno I didn't because hissy wrote that there's another bug to fix...

**Comment by hissy** [comment]
Oh, that was fixed with my second commit.

**Comment by Remo** [comment]
ah sorry, didn't notice. Will put this PR on my list, will take some time to test it though, lots of stuff going on..

**Comment by Remo** [comment]
The value in the option element is hard coded too `<option value="AM"` why do we need to compare it to a translated value?

**Comment by Remo** [comment]
I don't quite understand it, but I can reproduce the problem and I can see that your PR fixes it..

**Comment by hissy** [comment]
Because, the compared value is translated at this line. https://github.com/concrete5/concrete5/blob/e28d8244a7b6815cd275e3a786a72e0754a167f8/web/concrete/core/helpers/form/date_time.php#L117

**Comment by Remo** [comment]
:+1: thanks

**Pull request merged**
