### PR TITLE
Update SearchIndex on edit page attributes

### PR DESCRIPTION
**Pull request by LyDiaMo**
Resolved this problem: https://www.concrete5.org/developers/bugs/5-6-3-2/pagelist-filterbyattribute-get-wrong-results/

### CODE REVIEW

**Comment by Remo** [comment]
thanks @LyDiaMo! good catch

**Comment by melat0nin** [comment]
This hasn't worked for me (I'm already running 5.6.3.3. When I change a custom attribute's value in the page properties dialogue the database isn't updated and I still get incorrect results. The correct method is being fired ('update_metadata') but the reindex isn't happening

**Comment by melat0nin** [comment]
I think the object that should be reindexed is `$nvc` (`$c->getVersionToModify()`), not `$c` itself.

**Comment by melat0nin** [comment]
Pull request here: https://github.com/concrete5/concrete5-legacy/pull/1911

**Pull request merged**
