### PR TITLE
Fixing captcha bug on form block

### PR DESCRIPTION
**Pull request by hissy**
Refs concrete5/concrete5-5.7.0@04cfa44edf552ce5ee9997df2586f5a64f0b2411

### CODE REVIEW

**Comment by Remo** [comment]
this is just about not showing the captcha when editing the form?

**Comment by hissy** [comment]
Yes, it is. Because we can't save a form block due to previewing.

**Comment by Remo** [comment]
we can save the form block, that was fixed a while ago in 5.6
https://github.com/hissy/concrete5/commit/a2b782adbbd3433b3de4dc5d6d38e3eea3961238

not sure which solution is better.. The one we have shows you the preview in a more precise way as it shows the captcha too.

**Comment by hissy** [comment]
Oh, I missed that commit.

**Pull request closed without merging**
