### PR TITLE
To prevent and to press the wrong "Discard My Edits"

### PR DESCRIPTION
**Pull request by acliss19xx**
By mistake in Version Comments input
To prevent and to press the " Discard My Edits "

### CODE REVIEW

**Comment by Remo** [comment]
not sure about the sentence, can we use "discard" without anything after it? Native speakers?

**Comment by Mesuva** [comment]
Discard is a verb, so it is ok to use it in this context, but I think it would better to include what you are discarding. So it's clearer if it is:

_Are you sure you want to discard your edits?_

**Comment by katzueno** [comment]
Let me follow-up what @acliss19xx wants to do from this PR.

This will display alert message when you try to close the Content block edit window without saving it.

Sometime I accidentally closed the edit window without saving it. And you get super depressed that you need to do it again.

So this is a good fail-safe method to prevent closing the edit window by accident.

**Comment by katzueno** [comment]
Oh... sorry.. I got what @Remo and @Mesuva are trying to say...

@acliss19xx san
How about this?

"Are you sure you want to discard this edit?"

Thanks

**Comment by katzueno** [comment]
OK he said he fixed the message strings.

**Comment by Remo** [comment]
@acliss19xx can't merge this as we've changed i18n.php to use json_encode to avoid problems with translations with `'` in it. Can you please pull the master branch?

**Pull request closed without merging**
