### PR TITLE
Tiny mce 3.5.11

### PR DESCRIPTION
**Pull request by Hypocrite**
Updated tinyMCE to the latest 3.5.11 version and tested all the templates for concrete5 specific changes.

### CODE REVIEW

**Comment by Remo** [comment]
as mentioned on skype, I am interesting in getting this into concrete5 to keep it alive and working with  IE11 but I think you have forgotten to rebase your master branch and thus created this PR on top of concrete5 version 5.5.2.2a1

**Comment by katzueno** [comment]
Oh cool. I thought I was going to work on it.
But oops.

Let me know if you need any help.

**Comment by Remo** [comment]
@katzueno Heikki and I are currently talking on Skype, there are a few styling issues. I'll try to run some tests later and then post another message. It would definitely help to get more feedback, but please wait till we've fixed them most basic issues.

**Comment by Hypocrite** [comment]
There were some issues with the first fork I made.

I created a new fork here:
https://github.com/Hypocrite/concrete5/tree/tinyMCE-3.5.11-update

Most of the styling issues should be now fixed but of course it would be nice if we can get more tests done.

**Comment by Hypocrite** [comment]
There is a new pull request done:
https://github.com/concrete5/concrete5/pull/1878

**Pull request closed without merging**
