### PR TITLE
Add trailing slashes in robots.txt

### PR DESCRIPTION
**Pull request by hissy**
Wow, my package listing page has been blocked long time by robots.txt.

http://notnil-creative.com/concrete5-packages/

These pages will also be blocked.

http://example.com/jobs-report/
http://example.com/mailing/

Let's add trailing slashes.

### CODE REVIEW

**Comment by Remo** [comment]
as a matter of fact we should remove some more things, check this https://github.com/concrete5/concrete5/pull/1865

**Comment by zanedev** [comment]
what does trailing slashes do on robots.txt?

**Comment by hissy** [comment]
See my examples.

/jobs-report/ is normal and valid page slug, but blocked with `Disallow: /jobs`

**Comment by Remo** [comment]
I understand, but the other pr is even more important as Google won't be able to detect your site as responsive..                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   From: Takuro HishikawaSent: Wednesday, February 4, 2015 19:20To: concrete5/concrete5Reply To: concrete5/concrete5Cc: Remo LaubacherSubject: Re: [concrete5] Add trailing slashes in robots.txt (#1880)See my examples.

/jobs-report/ is normal and valid page slug, but blocked with Disallow: /jobs 

—Reply to this email directly or view it on GitHub.

**Comment by zanedev** [comment]
wow I always thought it was exact matches in robots.txt good to know!

**Comment by hissy** [comment]
I think both issues are very important. We should announce that users should update their robots.txt, because it will not be updated automatically.

**Comment by Remo** [comment]
as mentioned in the other PR, I'd like to extend the upgrade script to check if robots.txt is writable and if it is, replace some of the existing entries. We can then display a warning to all other users..

**Comment by hissy** [comment]
Let's merge discussions about robots.txt. I close this PR.

**Pull request closed without merging**
