### PR TITLE
Enables to attach Workflows for Task/User/File permissions

### PR DESCRIPTION
**Pull request by hissy**
I'm working on the job that extend Workflow. It is able to attach Workflows for Page Permissions, but it is not able to attach custom Workflows for other permission categories. This request might fix this issue, but I'd like to hear the opinion from core team.

### CODE REVIEW

**Comment by Remo** [comment]
@hissy how well did you test this? As mentioned above, I don't have enough experience with workflows to judge this myself.

**Comment by hissy** [comment]
I developed a new workflow type for my client last year. This is the why I found this bug. So I and my client tested about this.

**Comment by Remo** [comment]
Well, I'm going to trust you on this one ;-)

**Comment by hissy** [comment]
Thanks

**Pull request merged**
